### ISSUE TITLE
Error when models are on another drive

### ISSUE THREAD

**Issue by masonc15** [MNeMoNiCuZ/sd-webui-thumbnailizer#5]
```
*** Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\sd-webui-thumbnailizer\scripts\thumbnailizer.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "C:\stable-diffusion-webui\extensions\sd-webui-thumbnailizer\scripts\thumbnailizer.py", line 369, in on_ui_tabs
        model_choices = [os.path.relpath(p, ckpt_dir) for p in relevant_model_paths]
      File "C:\stable-diffusion-webui\extensions\sd-webui-thumbnailizer\scripts\thumbnailizer.py", line 369, in <listcomp>
        model_choices = [os.path.relpath(p, ckpt_dir) for p in relevant_model_paths]
      File "C:\Program Files\Python310\lib\ntpath.py", line 747, in relpath
        raise ValueError("path is on mount %r, start on mount %r" % (
    ValueError: path is on mount 'C:', start on mount 'F:'
```

My install is on the C: drive but my model folder is on the F: drive.  Any help would be appreciated, thanks!

**Comment by MNeMoNiCuZ** [comment]
How are your models linked to another drive? Which setting are you using to link them there?

I have the same setup for myself, but I use symbolic links set up in Windows so it thinks they are all in the Stable diffusion/models-folder.

**Comment by MNeMoNiCuZ** [comment]
> `set COMMANDLINE_ARGS=--ckpt-dir "F:\Models"` in `webui-user.bat`.
> 
> That's interesting though, I didn't know symlinks worked.

Hey, I finally got around to looking into this.
I also get the same error as you do when I use this argument.

From reading this discussion, there are additional drawbacks with using the --ckpt-dir setup, namely that the normal checkpoint location isn't supported. And from my testing, it's acting very differently if I use that command. Meaning that the commands I use to switch checkpoints between thumbnail generation are no longer working, the model filtering isn't working and a few other issues.

I hope you were able to make it work with symlinks meanwhile. This keeps working great for me and I have my models on different drives as well.

As it is, I don't have the understanding or capacity to solve it.

I'll leave the topic open in case someone else is able to contribute a stable solution.

Claude gave me the following update, which got past the initial error:

```
def initialize_model_data():
    global all_model_names, all_model_paths, relevant_model_names, relevant_model_paths
    # Clear existing data
    all_model_names = []
    all_model_paths = []
    relevant_model_names = []
    relevant_model_paths = []

    # Set new data
    model_path = Path(ckpt_dir).resolve()  # Use resolve() to get the absolute path
    model_files = glob.glob(model_path.joinpath("**/*").as_posix(), recursive=True)

    for m in model_files:
        if Path(m).suffix in {".ckpt", ".safetensors"}:
            abs_path = os.path.abspath(m)  # Use absolute path
            rel_path = os.path.relpath(abs_path, model_path.as_posix())
            all_model_names.append(Path(rel_path).name)
            all_model_paths.append(abs_path)  # Store absolute path

            # Normalize the path for comparison
            normalized_path = Path(abs_path).as_posix()

            # Check if the model is in a blocked folder path
            is_blocked = False
            for path, enabled in blocked_paths:
                if normalized_path.startswith(os.path.abspath(path)):
                    is_blocked = enabled
                if normalized_path == os.path.abspath(path) and not enabled:
                    is_blocked = False
                    break

            if abs_path not in blocklist and not is_blocked:
                relevant_model_names.append(Path(rel_path).name)
                relevant_model_paths.append(abs_path)  # Store absolute path
                
                
                
    ######################## BLOCKLIST SECTION ########################
    with gr.Box(elem_classes="ch_box"):
        # Load the current blocklist

        # Modify the choices to use absolute paths
        model_choices = [p for p in all_model_paths]  # all_model_paths now contains absolute paths                

```


Good luck to anyone that tackles this.
